MASTER_INCOME_PROVINCE_SPSID="1cF3r4KbVS7SwdM3PjIqeSi_F6_ljwX90dJ0KxmF9Gq0"
MASTER_INDICATOR_SPSID="17FcLnySs0iTBF-kTRiRWbVqTDY3Zvcb9AIBOvB_1_hg"
MASTER_AREA_SPSID="1EZT31slt8yJ56VuX3PwS1vGBmsDRl8YeWTfl0QreV-4"
MASTER_YEAR_SPSID="1kvrTGaUtg1MA6ci8-Zvr-EQdqRSv_LHDRrlNz-aleRk"

MASTER_WORKSHEET="main"

CLEANED_DATA_DRIVE_FOLDER="1Jt5kwp5udHaMhm0N7VIWX6WrQpjPNFjr"
SCOPES=["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/spreadsheets"]
DEFAULT_NULL_VALUE = "--EMPTY VALUE DATA--"
SERVICE_ACCOUNT_FILE = "service-account-api.json"
METADATA_CLEANED_DATA = "1x-_0q2wNNWhNgkastq-Y9Ipi-oXdDEyz"
MERGED_DATA_SPS_ID = "1cxezORckD40WCM2BfZTvYoSEfE2z0Chyu6NheAKWGuo"
WAREHOUSE_DATA_SPS_ID = "1BaKE-i3kHmW-N-w5QScJmj33fZuSpY4CUBUMDEcaFes"